isim force add clk100mhz 0 -value 1 -time 5ns -repeat 10ns
wave add -radix bin clk100mhz
wave add -radix unsigned pc
wave add -radix unsigned pcplus4
wave add -radix unsigned nextpc
wave add -radix bin inst
wave add -radix hex isjump
wave add -radix hex ishalt
wave add -radix hex memtoreg
wave add -radix hex memwrite
wave add -radix hex isbranch
wave add -radix hex alusrc
wave add -radix hex regwrt
wave add -radix hex takebranch
wave add -radix hex /dm_comp/data_memory
wave add -radix hex /rf_comp/my_RF
wave add -radix unsigned rs
wave add -radix unsigned rt
wave add -radix unsigned rd
wave add -radix unsigned rfwriteregister
wave add -radix hex rfwrite
wave add -radix hex aluresult
wave add -radix hex imm32
wave add -radix hex rfwrite
wave add -radix hex rfread1
wave add -radix hex rfread2
wave add -radix hex dmresult
wave add -radix hex b
